main = traverse putStrLn
    [ ""
    , " +--------------------------------------------------------------------+"
    , " |                                                                    |"
    , " |  -sssssssssso`  ./+++++++++/`                                      |"
    , " |   `ossssssssss-  `:+++++++++/.                                     |"
    , " |     /ssssssssss/`  -/+++++++++:`                                   |"
    , " |      -ossssssssso.  `/+++++++++/.                                  |"
    , " |       `+ssssssssss:  `:/++++++++/-                                 |"
    , " |         :ssssssssss+`  ./+++++++++:`                               |"
    , " |          .ossssssssso-  `/+++++++++/.   -////////////////////////  |"
    , " |           `/ssssssssss/   -/++++++++/-   /sssssssssssssssssssssss  |"
    , " |             :ssssssssss+.  ./+++++++++:`  -osssssssssssssssssssss  |"
    , " |              .ossssssssss-  `:+++++++++/.  `+ssssssssssssssssssss  |"
    , " |               `/ssssssssss/   -++++++++++:`  ````````````````````  |"
    , " |               `/ssssssssss/   -+++++++++++/`    `````````````````  |"
    , " |              .ossssssssss-  `:+++++++++++++/-   /ssssssssssssssss  |"
    , " |             -ssssssssss+.  ./++++++++++++++++:`  :sssssssssssssss  |"
    , " |           `/ssssssssss/`  -/++++++++++++++++++/.  .osssssssssssss  |"
    , " |          .ossssssssso-  `/+++++++++/.:+++++++++/-  `:////////////  |"
    , " |         :ssssssssss+`  ./+++++++++:`  ./+++++++++:`                |"
    , " |       `+ssssssssss:  `:/++++++++/-     `:+++++++++/.               |"
    , " |      -ossssssssso.  `/+++++++++/.        -+++++++++/:              |"
    , " |     /ssssssssss+`  -/+++++++++:`          ./+++++++++/`            |"
    , " |   `ossssssssss-  `:+++++++++/-             `:+++++++++/-           |"
    , " |  -sssssssssso`  ./+++++++++/`                -++++++++++:          |"
    , " |  -sssssssssso`  ./+++++++++/`                -++++++++++:          |"
    , " |                                                                    |"
    , " +--------------------------------------------------------------------+"
    , ""
    ]
